name: Build inputstream.ffmpegdirect
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PACKAGE_NAME: 'inputstream.ffmpegdirect'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          arch: armhf
            
      
      - name: install versioned packages
        shell: alpine.sh --root {0}
        run: |
          apk add 
            gettext=0.21.1 \
            build-base \
            cmake \
            git \
            autoconf \
            automake
      
      - uses: actions/checkout@v4
        with:
          repository: 'xbmc/xbmc'
          ref: '21.0-Omega'
          path: xbmc

      - uses: actions/checkout@v4
        with:
          repository: 'xbmc/${{env.PACKAGE_NAME}}'
          ref: '21.3.7-Omega'
          path: ${{env.PACKAGE_NAME}}

      - name: Create build directory
        run: |
          mkdir ${{env.PACKAGE_NAME}}/build
      
      - name: cmake
        shell: alpine.sh {0}
        run: |
          cd ${{env.PACKAGE_NAME}}/build
          cmake -DADDONS_TO_BUILD=${{env.PACKAGE_NAME}} -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../xbmc/build/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons

      - name: make
        shell: alpine.sh {0}
        run: |
          cd ${{env.PACKAGE_NAME}}/build
          make -j$(nproc)