name: Build libzvbi
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: ['x86_64', 'x86', 'aarch64', 'armv7', 'armhf']
    runs-on: ubuntu-latest
    
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.arch }}
          branch: v3.21
          packages: >
            build-base
            cmake
            git
            autoconf
            automake
            gettext-dev
            libtool
            linux-headers
            musl-dev
      
      - run: |
          wget https://github.com/zapping-vbi/zvbi/archive/refs/tags/v0.2.44.tar.gz
          tar xf v0.2.44.tar.gz
          cd zvbi-0.2.44
          CONFIGURE=1 ./autogen.sh
          make
        shell: alpine.sh {0}