name: Build inputstream.ffmpegdirect
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          arch: armhf

      - run: cat /etc/alpine-release
        shell: alpine.sh {0}

      - run: uname -a
        shell: alpine.sh {0}
      
      - run: uname -p
        shell: alpine.sh {0}